### ISSUE TITLE
Additional .obb files

### ISSUE THREAD

**Issue by muzzyrost** [89z/googleplay#55]
Hello, thanks for great application. I've try to download `com.tencent.ig` but its downloading only main apk file. This game need .obb cache files for starting. Is there any chance to get this files?

**Comment by 89z** [comment]
Sorry, I don't think I want to support this. It is possible, but a few problems. First the app `com.tencent.ig` doesn't support `x86`, so any solution will need to be using ARM, which I don't like in general, as its hard to emulate. Further, even if this tool could download OBB, it seems the installation process is quite difficult:

https://musteresel.github.io/posts/2020/12/adb-transfer-android-app-between-devices-apk-and-obb.html

If you know some easy way to install OBB (ideally with ADB), then I will reconsider. Otherwise, I will only add this in response to a donation:

https://github.com/89z/googleplay/tree/v1.9.2/docs#will-you-add-features

If you wish to donate, let me know.

**Comment by 89z** [comment]
Correction, I think I found a way to get the combined file

**Comment by 89z** [comment]
Sorry, I dont think I want to support this. It is possible, but a few problems. First the app `com.tencent.ig` doesnt support `x86`, so any solution will need to be using ARM, which I dont like in general, as its hard to emulate. Further, even if this tool could download OBB, it seems the installation process is quite difficult:

https://musteresel.github.io/posts/2020/12/adb-transfer-android-app-between-devices-apk-and-obb.html

If you know some easy way to install OBB (ideally with ADB), then I will reconsider. Otherwise, I will only add this in response to a donation:

https://github.com/89z/googleplay/tree/v1.9.2/docs#will-you-add-features

If you wish to donate, let me know.

**Comment by 89z** [comment]
I see that its possible to get a single APK somehow:

https://apkpure.com/pubg-mobile-for-android/com.tencent.ig

but I am not going to download a 1 GB APK to do further testing. If you know a smaller app that uses OBB, I can reopen the issue. Otherwise, donation as previously mentioned.

**Comment by muzzyrost** [comment]
@89z `com.microsoft.office.officehubrow` is great for testing, it has x86 version and just 7MB obb file.

**Comment by 89z** [comment]
I haven't checked all apps yet, but it seems `com.microsoft.office.officehubrow` works fine without the OBB

**Comment by 89z** [comment]
OK `com.PirateBayGames.ZombieDefense2` might be a good example. It seems to start without the OBB, but does seem like its missing some stuff

**Comment by muzzyrost** [comment]
> I haven't checked all apps yet, but it seems `com.microsoft.office.officehubrow` works fine without the OBB

Yes, you can use it without obb file, but it contains additional fonts and libs for some languages. It's just useful example with small size. Other apps can't start without cache obb files.

**Comment by 89z** [comment]
`com.PirateBayGames.ZombieDefense2` does start without the OBB, but it seems to be missing some text in the main menu. I will do more testing.

**Comment by 89z** [comment]
OK I have played with this for 30 minutes now, I give up. I tried installing with ADB:

~~~
adb root
adb push com.PirateBayGames.ZombieDefense2 /storage/emulated/obb
~~~

Also by just dragging the Android folder containing the OBB to the device screen. Dragging seems to have worked:

~~~
/sdcard/Android/data/com.google.android.apps.docs/cache
/sdcard/Android/data/com.google.android.apps.docs/files
/sdcard/Android/data/com.google.android.apps.docs/files/pinned_docs_files_do_not_edit
/sdcard/Android/data/com.PirateBayGames.ZombieDefense2
/sdcard/Android/data/com.PirateBayGames.ZombieDefense2/cache
~~~

but when I start the app, it still seems to be missing the OBB information. If you can provide an example OBB app, and instruction on how to install it, I will proceed with this issue. Until then, issue is closed.

**Comment by 89z** [comment]
I think I figured it out

**Comment by 89z** [comment]
Looks like you can install the OBB like this (need the final slash):

~~~
adb push com.PirateBayGames.ZombieDefense2 /sdcard/Android/obb/
~~~

I will see about adding the OBB support.

**Comment by 89z** [comment]
This should be fixed now:

https://github.com/89z/googleplay/blob/e558e378caec2d15414ace4d2fb410c8474da530/delivery.go#L24-L27

if you have any problems let me know.

**Comment by muzzyrost** [comment]
Thanks! That is great solution. But it has small bug for some range of applications. APK Expansion files has next format `[main|patch].<expansion-version>.<package-name>.obb` info from https://developer.android.com/google/play/expansion-files

And when you try to download obb files for apps with main and patch expansion-version it downloads only apk. Few ids for tests:
`com.sigmateam.alienshootermobile.free` - 200 Mb
`com.naturalmotion.customstreetracer2` - 2 Gb
`com.bhvr.deadbydaylight` - 4 Gb

**Comment by 89z** [comment]
This should be fixed now:

https://github.com/89z/googleplay/blob/0ba3a0aeadff5f70fcf37a4a241acca29b46c46a/delivery.go#L79-L93

**Comment by 89z** [comment]
https://github.com/EFForg/apkeep/issues/93

**Comment by muzzyrost** [comment]
Now it's great! Thanks a lot @89z
