### ISSUE TITLE
Read device config from file

### ISSUE THREAD

**Issue by kotori2** [89z/googleplay#60]
https://github.com/89z/googleplay/blob/master/config.go
I would like to customize some fields in device config for non-split apks. Could we add an option to use config file in json?

**Comment by muzzyrost** [comment]
But it already has key for downloading just non-split files: `-s`

**Comment by kotori2** [comment]
@89z Exactly. But I still think it's better to have a config file instead of hardcoding everything into source code. I could add x86_64 support directly in config file instead of creating [my fork](https://github.com/kotori2/googleplay/commit/2bdba2e42fac70c1709b23e676beb8abb1995620) :D

**Comment by 89z** [comment]
If you wish for x86_64 support, please open new issue. Regarding a config file, I think its a good idea, but I would rather improve `googleplay.Phone`, than add support for config file at this time. If I add config file support, then people will just use their own config file, rather than post an issue in order to improve the existing config. I think this project is still small enough, that I would like to improve the exist config some more, before adding the option. I see you made a donation, thank you for that. However if I am to implement this feature, the minimum donation would need to be met:

https://github.com/89z/googleplay/tree/v1.9.3/docs#will-you-add-features

Also the change would be a private change to you, as I think not having the option is good right now, as detailed above.

**Comment by kotori2** [comment]
Agreed. Thanks!
