### ISSUE TITLE
403 Forbidden when auth

### ISSUE THREAD

**Issue by bit-rocket** [89z/googleplay#86]
Hi, @89z Thanks for your project.
I pulled the code down and built it successfully, but when I tried to run, 
```
./googleplay -email   MY_EMAIL   -password MY_PASS
```

it showed the error messages below,
```
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
	/root/software/googleplay/cmd/googleplay/main.go:61 +0x885
```
Could you help?

**Comment by bit-rocket** [comment]
I have tryied the email with password in play store page https://play.google.com/store/apps , it can login successfully.
I am not sure why the account can not work in the above case.

**Comment by 89z** [comment]
The login command works for me:

~~~
> googleplay -email srpen6@gmail.com -password PASSWORD
POST https://android.googleapis.com/auth
Create C:\Users\Steven\googleplay\token.json
~~~

Sorry, I no longer provide free help, as people were abusing it. If you wish to make a donation, I can help you to solve the problem here, via email or Discord. Otherwise, good luck to you.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/92
